theme: jekyll-theme-slate
title: 9. Supplementary Materials
description: This page contains supplementary materials for the paper 'Obstacles and Facilitators of Economic Integration of Immigrants in the UK Labour Market'.
